history.asc çevrildi
progit/progit2-tr pull request #21
Opened 2020-04-26 12:37 UTC by Ksenofanex

2020-04-26 13:22 UTC, huzeyfeborazan requested changes
Genel olarak guzel bir ceviri olmus, elinize saglik.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/help.asc
> +=== Yardım almak
Baslik oldugu icin "Yardim Almak" seklinde olsa sanki daha iyi olur.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/help.asc
> -These commands are nice because you can access them anywhere, even offline.
Bu cumlenin cevirisi atlanmis.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/help.asc
> +Eğer kullanım kılavuzu ve bu kitap sizin için yeterli değilse ve birebir birisi tarafından yardıma ihtiyacınız varsa, https://freenode.net[] adresinde bulunan Freenode IRC sunucusundaki `#git` ya da
"birebir birisi tarafından" ibaresi biraz kalabalik gibi duruyor. Onerim; ... birebir yardima ihtiyaciniz varsa veya ... kisisel veya sahsi ibaresi de kullanilabilir.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/history.asc
> +Bu da Linux'u geliştiren topluluğun(özellikle Linux'un yaratıcısı olan Linus Torvalds'ın) Bitkeeper'i kullanırken edindiği deneyimler üzerinden kendi dağıtık versiyon kontrol sistemini geliştirmek is
toplulugun sozcugunden sonra bir bosluk konulmasi lazim.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/history.asc
> +* Lineer olmayan geliştirme için güçlü destek(Binlerce paralel branş desteği)
branch diger bolumlerde nasil cevrilmis bilmiyorum ama "dal" daha uygun olur sanki. brans diye cevirilirse anlam kaymasi olabilir. Ayrica "destek" sozcugunden sonra yine bi bosluk olmasi lazim.

2020-04-26 13:22 UTC, huzeyfeborazan commented on book/01-introduction/sections/history.asc
> +(Daha fazlası için: https://github.com/progit/progit2-tr/blob/master/book/03-git-branching/sections/basic-branching-and-merging.asc ).
Link ana dokumandaki gibi degil, bunun sebebi nedir? chapter'a link vermek static link vermekten daha mantikli.

2020-04-26 13:27 UTC, Ksenofanex commented on book/01-introduction/sections/history.asc
> +(Daha fazlası için: https://github.com/progit/progit2-tr/blob/master/book/03-git-branching/sections/basic-branching-and-merging.asc ).
Ana dokumündaki linke tıkladığımda çalışmayan bir linke yönlendiriyordu. Hatalı olduğunu düşünerek bu şekilde yaptım. Nasıl olması gerektiğini gösterebilirseniz, doğru şekilde düzeltmek isterim.

2020-04-26 13:42 UTC, huzeyfeborazan commented on book/01-introduction/sections/history.asc
> +(Daha fazlası için: https://github.com/progit/progit2-tr/blob/master/book/03-git-branching/sections/basic-branching-and-merging.asc ).
Benim bildigim kadariyla o linkler kitap compile oldugunda olusturuluyor. Ben olsam onu degistirmeden birakirdim.

2020-04-26 13:45 UTC, Ksenofanex commented on book/01-introduction/sections/history.asc
> +(Daha fazlası için: https://github.com/progit/progit2-tr/blob/master/book/03-git-branching/sections/basic-branching-and-merging.asc ).
Düzelttim.

2020-04-26 13:55 UTC, huzeyfeborazan commented on book/01-introduction/sections/history.asc
> +* Hız
Burada iki tane parantez oncesi bosluk birakilmamis.

2020-04-26 14:28 UTC, huzeyfeborazan approved these changes

2020-04-26 14:28 UTC, huzeyfeborazan commented
Elinize saglik.

2020-04-26 14:33 UTC, Ksenofanex commented
> Elinize saglik.

Vaktiniz ve ilginiz için ben teşekkür ederim.

2020-04-28 14:47 UTC, gokaygurcan requested changes

2020-04-28 14:47 UTC, gokaygurcan commented on book/01-introduction/sections/history.asc
> +Bu da Linux'u geliştiren topluluğun (özellikle Linux'un yaratıcısı olan Linus Torvalds'ın) Bitkeeper'i kullanırken edindiği deneyimler üzerinden kendi dağıtık versiyon kontrol sistemini geliştirmek i
Bu cumlenin sonundaki `(((Linus Torvalds)))` kismi eksik. Onu da eklersek merge icin bir engel kalmayacak.

2020-04-28 16:04 UTC, gokaygurcan approved these changes

2020-04-29 09:27 UTC, Ksenofanex commented
Bir problem mi var Gökay bey, mergelemeyecek misiniz? @gokaygurcan

2020-04-29 09:35 UTC, gokaygurcan commented
:)

2020-04-29 09:36 UTC, merged