Çeviri
progit/progit2-tr pull request #22
Opened 2020-04-30 15:44 UTC by Ksenofanex

2020-04-30 21:22 UTC, gokaygurcan requested changes

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
> +RCS yama setlerini(dosyalar arasındaki farklılıklar) disk üzerinde özel bir formatta tutarak çalışır; daha sonra tüm yamaları bir araya getirerek herhangi bir zamanda herhangi bir dosyanın nasıl görü
Parantezden once bir bosluk eksik.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
> +Bu sistemler(CVS, Subversion ve Perforce gibi) bütün sürümlendirilmiş dosyaları barındıran tek bir sunucuya ve o sunucudaki dosyaları merkezî bir yerden sürekli denetleyen istemcilere sahipti. (((CVS
Parantez oncesi eksik bosluk burada da mevcut.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
>  If that server goes down for an hour, then during that hour nobody can collaborate at all or save versioned changes to anything they're working on.
Sanirim bu satir ceviri asamasinda referans olarak kullanilip sonra unutulmus.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
> +İşte tam da burada devreye Dağıtık Versiyon Kontrol Sistemleri(DVKS) giriyor.
Parantez.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
> +Bir DVKS'de(Git, Mercurial, Bazaar ya da Darcs gibi) istemciler sadece dosyaların son anlık görünümünü denetlemezler, daha çok depoyu deponun tam tarihiyle birlikte yansıtırlar.
Ve parantez.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/about-version-control.asc
> +Ayrıca bu sistemlerin çoğu birden çok uzak depoyla çalışmayı rahatlıkla kaldırabilir, o yüzden farklı gruplardan insanlarla farklı yollarla simültane bir şekilde rahatlıkla iş birliği yapabilirsiniz.
`simültane` yerine `es zamanli` desek daha yerinde bir ceviri olur mu acaba? simültane de cok Turkce degil zira.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/command-line.asc
> +Bu kitapta Git'i komut satırıyla birlikte kullanacağız.
`komut satiriyla birlikte` degil de `komut satiri uzerinde/uzerinden` gibi bir anlam daha dogru degil mi sizce de?

Orijinal metnin _command-line_ ve _command line_ diye iki farkli sekilde kullanmasi da ayri guzel bir karisiklik yaratmis.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/command-line.asc
> +Özellikle bilmeniz gereken şey ise, komut satırında __tüm__ Git komutlarını çalıştırabiliyor olmanızdır. Çoğu GKA(grafiksel kullanıcı arayüzü) sadelik için Git'in fonksiyonlarının sadece belli başlı,
Ve son bir parantez.

2020-04-30 21:22 UTC, gokaygurcan commented on book/01-introduction/sections/command-line.asc
> +O yüzden sizden macOS'daki Terminal'i ya da Windows'taki Komut İstemi'ni veya Powershell'i nasıl açacağınızı biliyor olmanızı bekliyoruz.
`PowerShell` ozel isim, oldugu gibi yazmak daha dogru olacaktir.

2020-04-30 21:24 UTC, gokaygurcan commented
Merhaba @Ksenofanex,

Cevirilere devam ettiginiz icin cok ama cok tesekkurler. Benim cok uzun suredir yapmak isteyip bir turlu vakit ayiramadigim seylerden birisi bu. Hic olmazsa review tarafinda elimden geldigince yardimci olmaya calisiyorum.

Sevgiler.

2020-05-01 10:11 UTC, Ksenofanex commented on book/01-introduction/sections/about-version-control.asc
> +Ayrıca bu sistemlerin çoğu birden çok uzak depoyla çalışmayı rahatlıkla kaldırabilir, o yüzden farklı gruplardan insanlarla farklı yollarla simültane bir şekilde rahatlıkla iş birliği yapabilirsiniz.
Haklısınız.

2020-05-01 10:17 UTC, Ksenofanex commented
@gokaygurcan Rica ederim, bunun gibi kaliteli, açık kaynak felsefesini benimsemiş kaynakların olabildiğince kişiye ulaşmasına katkıda bulunmaktan son derece memnunum. İlginiz ve vaktiniz için ben teşekkür ederim.

P.S.: Ne çektiysem bu parantezlerden çektim. :))

2020-05-01 17:36 UTC, gokaygurcan approved these changes

2020-05-01 17:36 UTC, merged

2020-05-01 17:36 UTC, gokaygurcan commented
Tekrar tesekkurler ^_^