Update ch07-git-tools.asc
progit/progit2-tr pull request #7
Opened 2018-02-17 22:02 UTC by realbaycan

Turkish translation

2018-02-17 22:18 UTC, gokaygurcan requested changes

2018-02-17 22:18 UTC, gokaygurcan commented on ch07-git-tools.asc
> +Şu ana kadar, kaynak kodu denetimi için bir Git deposu yönetmek veya korumak için ihtiyaç duyduğunuz günlük komut veiş akışlarının çoğunu öğrendiniz.
"komut ve iş akışları"

2018-02-17 22:41 UTC, realbaycan commented
I updated. Thank you.

2018-02-18 17:37 UTC, gokaygurcan approved these changes

2018-02-18 19:56 UTC, jnavila commented
Hi @gokaygurcan 
You approved the changes but did not merge them. I'd like to know if you need the requested privileges to do so.

BTW, at some point in the future, I would like to set up the automatic compilation of the book to pdf and ebook on this project (for download from git-scm.com). Let me know when the project is calm, so that I can make the necessary technical changes.

2018-02-18 21:48 UTC, gokaygurcan commented
Hi @jnavila,

After almost 3 years, people started to translate the book. Probably that's because of https://utopian.io/ and its rewarding system. But anyways, in the end we'll have a finished book and i care about that part most. 

The thing about this translations, mostly these people are using Google translate (not talking particularly about this PR or user, it's the general approach of the users of that platform) and it's not working 100% when you translate from En to Tr. I need to read all of it, make sure it's correct then accept the changes in an order. Right now i'm in reading phase and probably in couple of days they'll be merged back to the repository.

That'd be great to setup automated processes when we have at least some sections translated. If you need any help, you can just ping me.

2018-02-18 21:52 UTC, merged